#!/bin/sh

# PROVIDE: whereami
# KEYWORD: shutdown
PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

. /etc/rc.subr

name="whereami"
rcvar="whereami_enable"
extra_commands="status"

load_rc_config whereami
: ${whereami_enable:="NO"}

status_cmd="whereami_status"
start_cmd="whereami_start"
stop_cmd="whereami_stop"
restart_cmd="whereami_restart"

whereami="/usr/local/var/www/whereami"
pid="/usr/local/var/www/whereami/whereami.pid"
whereami_start() {
    whereami_stop;
    cd $whereami && sudo -u www sh -c ". ./bin/activate && python whereami.py $pid &"
}

whereami_stop() {
    for p in `cat $pid`
    do
        sudo -u www sh -c "kill $p 2> /dev/null"
    done
    echo "" > $pid
}

whereami_status() {
    if sockstat -4l | grep -q 6789
    then
        echo "\"whereami\" is running."
    else
        echo "\"whereami\" is not running."
    fi
}

whereami_restart() {
    whereami_stop
    whereami_start
}

run_rc_command "$1"
